### ISSUE TITLE
Downloader.py: error: unrecognized arguments: --mode catalog

### ISSUE THREAD

**Issue by ghost** [hashinami46/sakamichi-app-ts-cli#3]
Downloader.py: error: unrecognized arguments: --mode catalog is occured.
![image](https://github.com/hashinami46/sakamichi-app-ts-cli/assets/80163887/35ce98dd-9467-4a6f-bccf-c8015ec596db)
I think mode is not defined in Downloader.py....
Please check this error.

**Comment by hashinami46** [comment]
Seems that I forgot to push the latest python code 😅. A minute

**Comment by ghost** [comment]
> Seems that I forgot to push the latest python code 😅. A minute

Thank you for your answer. I've been looking for the problem for 5 days🤣

**Comment by hashinami46** [comment]
I already updated the code. Try it! You can just replace the "Downloader.py".

**Comment by ghost** [comment]
Hmm... it seems that another error is occured...?
![image](https://github.com/hashinami46/sakamichi-app-ts-cli/assets/80163887/ddc973df-97b2-4e50-9220-10a4c4dae26e)

**Comment by hashinami46** [comment]
Seems that there are some problems with the minified code. Gonna check it later. Little bit busy lately :)

**Comment by ghost** [comment]
Thanks for the update.
I sent you a coffee, so check it out!

**Comment by ghost** [comment]
![image](https://github.com/hashinami46/sakamichi-app-ts-cli/assets/80163887/7ee7eee4-88b0-43e9-bacf-fd07069c89a9)
Python error occured when downloading Sakukoi in local mode. But, this error is not occured in catalog mode.
I'd like to create a catalog, and if you don't mind, can you tell me how to do that?
Thank you as always.

**Comment by hashinami46** [comment]
Seems that there are some errors with the UnityPy module. Gonna check it later. Maybe tonight.
