### ISSUE TITLE
[ windows ] hinakoi download error

### ISSUE THREAD

**Issue by downforsoon** [hashinami46/sakamichi-app-ts-cli#8]
This problem arises when downloading hinakoi card:
![image](https://github.com/hashinami46/sakamichi-app-ts-cli/assets/168158293/528c66d8-f9f6-40f8-bf48-0c26d5809a9b)
```
Data length      : 118587
Requested assets : hinakoi_card
Length           : 35747
Requested length : 35747 (0 to 0)
Mode             : catalog
Whoops, server error
Whoops, an error named Error occured
```
But sakukoi and Unison work just fine

**Comment by hashinami46** [comment]
The catalog is outdated..

**Comment by downforsoon** [comment]
okay,I'll try to get data from android data,thanks for reply!
